server:
  port: ${CLIENTJDR_PORT:8080}
  cors:
    allowedOrigin: ${http://localhost:5173/:*}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:clientJDRDocker}
    username: ${DB_USER:clientJDR}
    password: ${DB_PASSWORD:clientjdr}
    driver-class-name: org.postgresql.Driver
  jpa:
     generate-ddl: true
     properties:
       hibernate:
         ddl-auto: create
         dialect: org.hibernate.dialect.PostgreSQLDialect
     sql:
       init:
         mode: always
     liquibase:
       enabled: false

